[packages.crate1]
versioned_files = ["src/crate1/Cargo.toml"]
changelog = "src/crate1/CHANGELOG.md"
scopes = ["crate1"]

[packages.crate2]
versioned_files = ["src/crate2/Cargo.toml"]
changelog = "src/crate1/CHANGELOG.md"
scopes = ["crate2"]

[[workflows]]
name = "prepare-release"

[[workflows.steps]]
command = "git switch -c release"
type = "Command"

[[workflows.steps]]
ignore_conventional_commits = true
type = "PrepareRelease"

[[workflows.steps]]
command = "git add Cargo.lock"
type = "Command"

[[workflows.steps]]
command = "git commit -m \"chore: prepare release\""
type = "Command"

[[workflows.steps]]
command = "git push --force --set-upstream origin release"
type = "Command"

[[workflows.steps]]
base = "main"
type = "CreatePullRequest"

[workflows.steps.title]
template = "chore: prepare release"

[workflows.steps.body]
template = "This PR was created by Knope. Merging it will create a new release"

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"

[github]
owner = "doc-E-brown"
repo = "knopeWorkspaceTest"
